name: SvarttDupePlugin
version: '1.1.0'
main: me.hatesvartt.svarttDupePlugin.SvarttDupePlugin
api-version: '1.21'
authors: [ hatesvartt ]
description: Various dupe methods made configurable.
folia-supported: true