name: SvarttDupePlugin
version: '1.2.1'
main: me.hatesvartt.svarttDupePlugin.SvarttDupePlugin
api-version: '1.21'
authors: [ hatesvartt ]
description: Various dupe methods made configurable.
folia-supported: true

commands:
  dupe:
    description: Shows the current dupe plugin config.
    usage: /dupe
